# Spring Boot configuration
spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CANOPY_KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${CANOPY_KEYCLOAK_JWK_SET_URI}

server:
  port: 8082
  servlet.context-path: /api/user/v1

database:
  db-user: ${dbuser}
  db-password: ${password}
  host: ${host}
  port: ${port}
  db-name: ${dbname}
  db-driver-class-name: ${dbDriverClassName}

management:
  endpoint:
    health:
      enabled: true
      show-details: never
    shutdown:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,shutdown

hub:
  supportEmail: ${supportEmail}
  emailQueue: ${EmailQueue}

logging:
  level:
    root: warn
    userservice:
      UserServiceApplication: info
    org.springframework.web.servlet:
      DispatcherServlet: trace
      mvc.method.annotation:
        HttpEntityMethodProcessor: trace

keycloak:
  realm: ${CANOPY_KEYCLOAK_REALM}
  resource: ${CANOPY_KEYCLOAK_CLIENT_ID}

---
# DEV

spring:
  config:
    import: aws-secretsmanager:${AWS_SECRET_NAME}
    activate:
      on-profile: dev
  cloud.aws.region.static: us-east-1
  jpa:
    show-sql: true
  security:
    user:
      name: ${CANOPY_SPRING_MANAGEMENT_USER}
      password: ${CANOPY_SPRING_MANAGEMENT_PASSWORD}

management:
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "[%boldMagenta(USER)] [%boldGreen(DEV)] %d{yyyy-MM-dd HH:mm:ss.SSS} %highlight([%5p]) --- [%cyan(%15.15t)] %-40.40logger{1.} %boldYellow(::) %m%n%wEx"
---
# TEST

spring:
  config:
    import: aws-secretsmanager:${AWS_SECRET_NAME}
    activate:
      on-profile: test

  cloud.aws.region.static: us-east-1

logging:
  pattern:
    console: "[USER] [TEST] %d{yyyy-MM-dd HH:mm:ss.SSS} [%5p] --- [%15.15t] %-40.40logger{1.} :: %m%n%wEx"

---
# PROD

spring:
  config:
    import: aws-secretsmanager:${AWS_SECRET_NAME}
    activate:
      on-profile: prod
  cloud.aws.region.static: us-east-1

logging:
  pattern:
    console: "[USER] [PROD] %d{yyyy-MM-dd HH:mm:ss.SSS} [%5p] --- [%15.15t] %-40.40logger{1.} :: %m%n%wEx"

